Fix handling of primitive type classes
In cases when metadata contained `@Serializer(forClass = int.class)` `int.class` part was treated as a class element value, and previously, in the refactored method, its internal className was calculated to be null as primitive class names were not taken into account apparently. It led to stacktrace like this:
```
java.lang.NullPointerException: Cannot invoke "String.length()" because "className" is null
	at com.guardsquare.proguard.kotlin.printer.internal.Context.className(Context.java:83)
	at com.guardsquare.proguard.kotlin.printer.internal.AnnotationPrinter.visitClassElementValue(AnnotationPrinter.java:138)
        ...
```
This diff adds a primitive type class check to have the name derived correctly.